### ISSUE TITLE
problem with banner viewvability

### ISSUE THREAD

**Issue by dmitruss** [fbsamples/audience-network-support#2]
![pasted_image_at_2016_03_12_12_03_am_720](https://cloud.githubusercontent.com/assets/1777197/13987125/1f9a130c-f117-11e5-9c1e-5f24c86adce4.png)

**Comment by dmitruss** [comment]
SDK 4.10.1

**Comment by jch7557** [comment]
Hi dmitruss,

Thanks for sharing your integration issue.
As I can take a guess from the screen shot, it relates to ad refresh.
For us to look into the issue, can you please provide a code snippet on demo the integration and issue? We can start from there.
