### ISSUE TITLE
Using Native Ads in UITableView

### ISSUE THREAD

**Issue by saintjab** [fbsamples/audience-network-support#3]
This is not an issue, I just need help with implementing Native Ads in UITableView. I am implementing about 5 Native Ads in a tableview. How do I registerViewForInteraction for all the ads in the tableview? I am loading different ad at different indexPath and on didSelectRowAtIndexPath, I want to register the view for interaction but its not working.

**Comment by jch7557** [comment]
To use this feature correctly, the native ad has to be unregistered from previous view like:
[self.nativeAd unregisterView];

Then register the specific view like this:
[nativeAd registerViewForInteraction:self.adUIView withViewController:self];

The Facebook SDK contains a tutorial sample project which includes a TableView demo. The detail can be referred in the SDK under Samples/FBAudienceNetwork/NativeAdSample/NativeAdSample/TableviewController.m.

**Comment by saintjab** [comment]
Hi @jch7557, thanks for the pointer. Unfortunately, I am using ASCellNode and ASTableView from The AsyncDisplayKit and because I am using customised Cells for the table, I need to manually capture the click events of each cell to determine the type and fire the appropriate method. Anyway I can manually handle the clicks? Thanks

**Comment by saurabh1939** [comment]
I have implemented facebook native Ads in UITableView, for first 1-2 times it clickable but when I scroll tableview and come again back to the same cell, now Ads are not clicking, I am using swift 3.2 Below is the cell implementation. 

let ad = adsManager.nextNativeAd
let cell = self.tableHome.dequeueReusableCell(withIdentifier: "HomeAdsTableViewCell", for: indexPath) as! HomeAdsTableViewCell
cell.message.text = ad?.body
cell.title.text = ad?.title
cell.callToActionButton.setTitle(ad?.callToAction, for: .normal)

if let pic = ad?.coverImage {
    cell.postImage.setImageWithIndicator(imageUrl:pic.url.absoluteString)
}

ad?.registerView(forInteraction: cell.postView, with: self)
cell.selectionStyle=UITableViewCellSelectionStyle.none

return cell
